id = "yulang"
name = "Yulang"
description = "Yulang language support"
version = "0.0.8"
schema_version = 1
authors = ["momota"]
repository = "https://github.com/momota1029/yulang-zed"

[grammars.yulang]
repository = "https://github.com/momota1029/tree-sitter-yulang"
commit = "bd05e120a9cbe268fff6549e7708639c9a3ff2d2"

[language_servers.yulang-lsp]
name = "Yulang LS"
languages = ["Yulang"]
